### ISSUE TITLE
update 3d viewer

### ISSUE THREAD

**Issue by toloudis** [allen-cell-animated/cell-feature-explorer#115]
## Use Case

website-3d-cell-viewer has new UI and is ready to be adopted by CFE

## Solution

bump included version of website-3d-cell-viewer.   
note that we are still expecting minor bug fixes and new icons.

**Comment by frasercl** [comment]
Branches [feature/toolbar](/allen-cell-animated/cell-feature-explorer/tree/feature/toolbar) and [feature/style-organization](/allen-cell-animated/cell-feature-explorer/tree/feature/style-organization) have changes that should be merged as part of this task. Depending on sequencing with allen-cell-animated/website-3d-cell-viewer#42, #88 may need to be merged concurrently as well.
