### ISSUE TITLE
Add metadata for download and other updates to CFE homepage

### ISSUE THREAD

**Issue by lynwilhelm** [allen-cell-animated/cell-feature-explorer#117]
## Use Case
This work came about due to changes to the data downloading page on allcell.org. We needed to add ability to download metadata.

- Need metadata download links added (directed from data downloads page on allencell.org)
- Need various other updates to page based on this implementation and revamp

## Acceptance

- Add download section for metadata
- Lock header bar when scrolling occurs (Users will be sent to the metadata section anchor point from website so this will help users know where they are)
- Increase “Cell Feature Explorer” font size
- Add a new top section of content
- Update content (text)

Design link: https://xd.adobe.com/view/4ec04a8c-535f-4158-b870-2e96d117f41c-1b93/

Contacts:
Lyndsay - design
Janani/Graham - content writing
Thao - website mgmt

## Alternatives

_Please describe any alternatives you've considered, even if you've dismissed them_

**Comment by meganrm** [comment]
@dan I don't see the actual link itself anywhere. is it just the default quilt page?

**Comment by meganrm** [comment]
@lynwilhelm I added some additional questions to the design page
