### ISSUE TITLE
Icon button with transparent background-color is hard to see on white

### ISSUE THREAD

**Issue by thao-do** [allen-cell-animated/cell-feature-explorer#160]
### Description
- Design
- Maybe consider a background for all icon buttons in the viewport, currently they have transparent background, when a user changes the viewport color to any other color than the default black, the icons can become hard to see (and they also have a faint shadow). It's also inconsistent when the other types of button do have background color.

<img width="829" alt="Screenshot 2024-01-17 at 1 34 49 PM" src="https://github.com/allen-cell-animated/cell-feature-explorer/assets/25212364/5ba9187a-ea6b-43bc-b896-e880b5c19815">

***
_Below to be filled out by UX during kickoff Q&A to the best of current understanding_

### Size
_Effort level (xs, sm, m, lg, xl)_

### Scope
_What will we do? What will we NOT do?_

### User needs statement(s)
As a _[type of user]_, I need/want to _[action(s)]_, so that I can _[goal]_.

### Additional notes
_Knowns/unknowns, stakeholders, time/dependency considerations, deliverables_

**Comment by ShrimpCryptid** [comment]
Closed by #88!

**Comment by toloudis** [comment]
> Closed by #88!

#88 seems to be a draft PR that is not merged yet?  Is closing this premature?
