### ISSUE TITLE
update cfe to use latest w3cv

### ISSUE THREAD

**Issue by toloudis** [allen-cell-animated/cell-feature-explorer#163]

**Comment by ShrimpCryptid** [comment]
![image](https://github.com/allen-cell-animated/cell-feature-explorer/assets/30200665/020addf4-1421-4b3b-b5ae-9e56558b0608)

Works with pretty minimal changes. Branch here: https://github.com/allen-cell-animated/cell-feature-explorer/tree/feat/upgrade-w3cv
