### ISSUE TITLE
Error: Tried to use a closed loader when switching between XY modes

### ISSUE THREAD

**Issue by ShrimpCryptid** [allen-cell-animated/cell-feature-explorer#220]
## Description

Error: Tried to use a closed loader

Switching between XY modes with a contour channel enabled makes the contour channel fail on the new cell. Also, sometimes you get an error message.

## Expected Behavior

_What did you expect to happen instead?_

## Reproduction

1. Turn on the contour channel.
2. Switch to XY view mode.
3. Switch to another cell.
4. Try reenabling the contour channel. (You may see the error message)

## Environment

_Any additional information about your environment. E.g. OS version, python version, browser etc._

**Comment by toloudis** [comment]
Does w3cv standalone have this behavior when using the Load button?

**Comment by ShrimpCryptid** [comment]
Doesn't look like it, because the view mode gets reset to 3D when a new file is loaded.
